import { Link } from 'react-router-dom';
import { ShieldCheckIcon, EnvelopeIcon, DocumentTextIcon } from '@heroicons/react/24/outline';

const Privacy = () => {
    return (
        <div className="min-h-screen bg-gradient-to-br from-gray-50 via-blue-50 to-purple-50">
            {/* Header */}
            <div className="bg-white shadow-sm border-b border-gray-200">
                <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
                    <Link to="/" className="inline-flex items-center text-primary-600 hover:text-primary-700 font-semibold mb-4">
                        ← Back to Home
                    </Link>
                    <div className="flex items-center gap-4">
                        <div className="h-12 w-12 bg-gradient-to-br from-primary-500 to-accent-500 rounded-xl flex items-center justify-center shadow-lg">
                            <ShieldCheckIcon className="h-7 w-7 text-white" />
                        </div>
                        <div>
                            <h1 className="text-3xl font-bold text-gray-900">Privacy Policy</h1>
                            <p className="text-sm text-gray-500 mt-1">Last Updated: December 2, 2024</p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Content */}
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
                <div className="bg-white rounded-2xl shadow-xl border border-gray-200 overflow-hidden">
                    <div className="p-8 sm:p-12 space-y-8">

                        {/* Introduction */}
                        <section>
                            <p className="text-gray-700 leading-relaxed">
                                Welcome to ClearComment. We are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, store, and protect your data when you use our Facebook comment moderation service.
                            </p>
                        </section>

                        {/* 1. Information We Collect */}
                        <section>
                            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
                                <DocumentTextIcon className="h-6 w-6 mr-2 text-primary-600" />
                                1. Information We Collect
                            </h2>
                            <div className="space-y-4 text-gray-700">
                                <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
                                    <h3 className="font-semibold text-gray-900 mb-2">1.1 Account Information</h3>
                                    <ul className="list-disc list-inside space-y-1 ml-4">
                                        <li>Email address (from Facebook or Google login)</li>
                                        <li>Name and profile picture (if provided by authentication provider)</li>
                                        <li>User ID (generated by our authentication system)</li>
                                    </ul>
                                </div>

                                <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
                                    <h3 className="font-semibold text-gray-900 mb-2">1.2 Facebook Page Data</h3>
                                    <ul className="list-disc list-inside space-y-1 ml-4">
                                        <li>Facebook Page IDs and names you connect to our service</li>
                                        <li>Page access tokens (encrypted and securely stored)</li>
                                        <li>Page metadata (category, follower count, etc.)</li>
                                    </ul>
                                </div>

                                <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
                                    <h3 className="font-semibold text-gray-900 mb-2">1.3 Comment Data</h3>
                                    <ul className="list-disc list-inside space-y-1 ml-4">
                                        <li>Comment text and metadata (author, timestamp, post ID)</li>
                                        <li>Comment status (visible, hidden, deleted)</li>
                                        <li>Moderation actions taken (manual or automated)</li>
                                        <li>Moderation rules and keywords you create</li>
                                    </ul>
                                </div>

                                <div className="bg-gray-50 rounded-lg p-6 border border-gray-200">
                                    <h3 className="font-semibold text-gray-900 mb-2">1.4 Usage Data</h3>
                                    <ul className="list-disc list-inside space-y-1 ml-4">
                                        <li>Log data (IP address, browser type, access times)</li>
                                        <li>Feature usage and interaction patterns</li>
                                        <li>Error logs and diagnostic information</li>
                                    </ul>
                                </div>
                            </div>
                        </section>

                        {/* 2. How We Use Your Information */}
                        <section>
                            <h2 className="text-2xl font-bold text-gray-900 mb-4">2. How We Use Your Information</h2>
                            <div className="space-y-3 text-gray-700">
                                <p>We use the collected information for the following purposes:</p>
                                <ul className="list-disc list-inside space-y-2 ml-4">
                                    <li><strong>Comment Moderation:</strong> To automatically detect and hide spam, inappropriate, or rule-violating comments on your Facebook pages</li>
                                    <li><strong>Service Delivery:</strong> To provide, maintain, and improve our comment moderation features</li>
                                    <li><strong>Analytics:</strong> To generate insights about comment activity, moderation patterns, and service performance</li>
                                    <li><strong>Communication:</strong> To send you service updates, security alerts, and support messages</li>
                                    <li><strong>Security:</strong> To detect, prevent, and address technical issues, fraud, and abuse</li>
                                    <li><strong>Compliance:</strong> To comply with legal obligations and enforce our Terms of Service</li>
                                </ul>
                            </div>
                        </section>

                        {/* 3. How We Store Your Data */}
                        <section>
                            <h2 className="text-2xl font-bold text-gray-900 mb-4">3. How We Store Your Data</h2>
                            <div className="space-y-4 text-gray-700">
                                <div className="bg-blue-50 rounded-lg p-6 border border-blue-200">
                                    <h3 className="font-semibold text-gray-900 mb-2">🔒 Secure Cloud Storage</h3>
                                    <p>All data is stored in <strong>Google Firebase Firestore</strong>, a secure, encrypted cloud database service that complies with industry-standard security practices including:</p>
                                    <ul className="list-disc list-inside space-y-1 ml-4 mt-2">
                                        <li>Encryption at rest and in transit (TLS/SSL)</li>
                                        <li>Regular security audits and compliance certifications</li>
                                        <li>Automatic backups and disaster recovery</li>
                                        <li>Geographic data residency controls</li>
                                    </ul>
                                </div>

                                <div className="bg-blue-50 rounded-lg p-6 border border-blue-200">
                                    <h3 className="font-semibold text-gray-900 mb-2">🔑 Access Control</h3>
                                    <p>Access to your data is restricted to:</p>
                                    <ul className="list-disc list-inside space-y-1 ml-4 mt-2">
                                        <li>You (via your authenticated account)</li>
                                        <li>Our backend services (using secure API keys)</li>
                                        <li>Authorized personnel (only for support and maintenance)</li>
                                    </ul>
                                </div>

                                <div className="bg-blue-50 rounded-lg p-6 border border-blue-200">
                                    <h3 className="font-semibold text-gray-900 mb-2">⏱️ Data Retention</h3>
                                    <ul className="list-disc list-inside space-y-1 ml-4">
                                        <li>Account data: Retained until you delete your account</li>
                                        <li>Comment data: Retained for 90 days, then automatically deleted</li>
                                        <li>Action logs: Retained for 30 days for audit purposes</li>
                                        <li>Deleted data: Permanently removed within 30 days</li>
                                    </ul>
                                </div>
                            </div>
                        </section>

                        {/* 4. Data Sharing */}
                        <section>
                            <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Data Sharing and Third Parties</h2>
                            <div className="space-y-3 text-gray-700">
                                <p className="font-semibold">We do NOT sell, rent, or trade your personal information to third parties.</p>
                                <p>We may share data only in the following limited circumstances:</p>
                                <ul className="list-disc list-inside space-y-2 ml-4">
                                    <li><strong>Facebook:</strong> We use Facebook's Graph API to access and moderate comments. Facebook's own privacy policy applies to their services.</li>
                                    <li><strong>Service Providers:</strong> We use trusted third-party services (Firebase, Railway) to host and operate our platform. These providers have strict data protection agreements.</li>
                                    <li><strong>Legal Requirements:</strong> We may disclose information if required by law, court order, or government request.</li>
                                    <li><strong>Business Transfers:</strong> In the event of a merger or acquisition, your data may be transferred to the new entity (you will be notified).</li>
                                </ul>
                            </div>
                        </section>

                        {/* 5. Your Rights */}
                        <section>
                            <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Your Rights and Choices</h2>
                            <div className="space-y-4 text-gray-700">
                                <p>You have the following rights regarding your personal data:</p>

                                <div className="grid md:grid-cols-2 gap-4">
                                    <div className="bg-green-50 rounded-lg p-4 border border-green-200">
                                        <h3 className="font-semibold text-gray-900 mb-2">✅ Access</h3>
                                        <p className="text-sm">Request a copy of all data we have about you</p>
                                    </div>
                                    <div className="bg-green-50 rounded-lg p-4 border border-green-200">
                                        <h3 className="font-semibold text-gray-900 mb-2">✏️ Correction</h3>
                                        <p className="text-sm">Update or correct inaccurate information</p>
                                    </div>
                                    <div className="bg-green-50 rounded-lg p-4 border border-green-200">
                                        <h3 className="font-semibold text-gray-900 mb-2">🗑️ Deletion</h3>
                                        <p className="text-sm">Request deletion of your account and all associated data</p>
                                    </div>
                                    <div className="bg-green-50 rounded-lg p-4 border border-green-200">
                                        <h3 className="font-semibold text-gray-900 mb-2">📥 Export</h3>
                                        <p className="text-sm">Download your data in a portable format</p>
                                    </div>
                                    <div className="bg-green-50 rounded-lg p-4 border border-green-200">
                                        <h3 className="font-semibold text-gray-900 mb-2">🚫 Opt-Out</h3>
                                        <p className="text-sm">Unsubscribe from marketing communications</p>
                                    </div>
                                    <div className="bg-green-50 rounded-lg p-4 border border-green-200">
                                        <h3 className="font-semibold text-gray-900 mb-2">🔒 Restrict</h3>
                                        <p className="text-sm">Limit how we process your data</p>
                                    </div>
                                </div>

                                <div className="bg-yellow-50 rounded-lg p-6 border border-yellow-200 mt-4">
                                    <h3 className="font-semibold text-gray-900 mb-2">How to Exercise Your Rights:</h3>
                                    <p>To exercise any of these rights, please contact us at <a href="mailto:privacy@clearcomment.com" className="text-primary-600 hover:text-primary-700 font-semibold">privacy@clearcomment.com</a></p>
                                    <p className="mt-2 text-sm">We will respond to your request within 30 days.</p>
                                </div>
                            </div>
                        </section>

                        {/* 6. Cookies and Tracking */}
                        <section>
                            <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Cookies and Tracking Technologies</h2>
                            <div className="space-y-3 text-gray-700">
                                <p>We use cookies and similar technologies to:</p>
                                <ul className="list-disc list-inside space-y-2 ml-4">
                                    <li>Keep you logged in to your account</li>
                                    <li>Remember your preferences and settings</li>
                                    <li>Analyze usage patterns and improve our service</li>
                                    <li>Prevent fraud and enhance security</li>
                                </ul>
                                <p className="mt-4">You can control cookies through your browser settings. Note that disabling cookies may limit some functionality of our service.</p>
                            </div>
                        </section>

                        {/* 7. Children's Privacy */}
                        <section>
                            <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Children's Privacy</h2>
                            <div className="bg-red-50 rounded-lg p-6 border border-red-200">
                                <p className="text-gray-700">
                                    Our service is <strong>not intended for children under 13 years of age</strong>. We do not knowingly collect personal information from children. If you are a parent or guardian and believe your child has provided us with personal information, please contact us immediately, and we will delete such information.
                                </p>
                            </div>
                        </section>

                        {/* 8. International Data Transfers */}
                        <section>
                            <h2 className="text-2xl font-bold text-gray-900 mb-4">8. International Data Transfers</h2>
                            <div className="space-y-3 text-gray-700">
                                <p>Your data may be transferred to and processed in countries other than your own. We ensure that such transfers comply with applicable data protection laws through:</p>
                                <ul className="list-disc list-inside space-y-2 ml-4">
                                    <li>Standard contractual clauses approved by regulatory authorities</li>
                                    <li>Adequacy decisions recognizing equivalent data protection</li>
                                    <li>Your explicit consent where required</li>
                                </ul>
                            </div>
                        </section>

                        {/* 9. Security */}
                        <section>
                            <h2 className="text-2xl font-bold text-gray-900 mb-4">9. Security Measures</h2>
                            <div className="space-y-3 text-gray-700">
                                <p>We implement industry-standard security measures to protect your data:</p>
                                <ul className="list-disc list-inside space-y-2 ml-4">
                                    <li>End-to-end encryption for data transmission</li>
                                    <li>Encrypted storage of sensitive information (access tokens)</li>
                                    <li>Regular security audits and vulnerability assessments</li>
                                    <li>Access controls and authentication mechanisms</li>
                                    <li>Monitoring and logging of suspicious activities</li>
                                </ul>
                                <p className="mt-4 text-sm italic">While we strive to protect your data, no method of transmission over the internet is 100% secure. We cannot guarantee absolute security.</p>
                            </div>
                        </section>

                        {/* 10. Changes to Privacy Policy */}
                        <section>
                            <h2 className="text-2xl font-bold text-gray-900 mb-4">10. Changes to This Privacy Policy</h2>
                            <div className="space-y-3 text-gray-700">
                                <p>We may update this Privacy Policy from time to time. When we do:</p>
                                <ul className="list-disc list-inside space-y-2 ml-4">
                                    <li>We will update the "Last Updated" date at the top of this page</li>
                                    <li>We will notify you via email if changes are material</li>
                                    <li>Your continued use of the service constitutes acceptance of the updated policy</li>
                                </ul>
                                <p className="mt-4">We encourage you to review this Privacy Policy periodically.</p>
                            </div>
                        </section>

                        {/* Contact Information */}
                        <section className="bg-gradient-to-r from-primary-50 to-accent-50 rounded-xl p-8 border border-primary-200">
                            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
                                <EnvelopeIcon className="h-6 w-6 mr-2 text-primary-600" />
                                11. Contact Us
                            </h2>
                            <div className="space-y-3 text-gray-700">
                                <p>If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:</p>
                                <div className="bg-white rounded-lg p-6 mt-4 space-y-2">
                                    <p><strong>Email:</strong> <a href="mailto:privacy@clearcomment.com" className="text-primary-600 hover:text-primary-700">privacy@clearcomment.com</a></p>
                                    <p><strong>Support:</strong> <a href="mailto:support@clearcomment.com" className="text-primary-600 hover:text-primary-700">support@clearcomment.com</a></p>
                                    <p><strong>Data Protection Officer:</strong> <a href="mailto:dpo@clearcomment.com" className="text-primary-600 hover:text-primary-700">dpo@clearcomment.com</a></p>
                                    <p className="text-sm text-gray-500 mt-4">We will respond to all inquiries within 30 days.</p>
                                </div>
                            </div>
                        </section>

                        {/* GDPR & CCPA Compliance */}
                        <section>
                            <h2 className="text-2xl font-bold text-gray-900 mb-4">12. GDPR & CCPA Compliance</h2>
                            <div className="grid md:grid-cols-2 gap-6">
                                <div className="bg-blue-50 rounded-lg p-6 border border-blue-200">
                                    <h3 className="font-semibold text-gray-900 mb-2">🇪🇺 GDPR (EU Users)</h3>
                                    <p className="text-sm text-gray-700">If you are located in the European Economic Area (EEA), you have additional rights under GDPR, including the right to lodge a complaint with your local data protection authority.</p>
                                </div>
                                <div className="bg-blue-50 rounded-lg p-6 border border-blue-200">
                                    <h3 className="font-semibold text-gray-900 mb-2">🇺🇸 CCPA (California Users)</h3>
                                    <p className="text-sm text-gray-700">California residents have the right to know what personal information we collect, request deletion, and opt-out of the sale of personal information (we do not sell your data).</p>
                                </div>
                            </div>
                        </section>

                    </div>
                </div>

                {/* Footer Links */}
                <div className="mt-8 text-center space-x-6">
                    <Link to="/terms" className="text-primary-600 hover:text-primary-700 font-semibold">
                        Terms of Service
                    </Link>
                    <Link to="/" className="text-gray-600 hover:text-gray-700">
                        Back to Home
                    </Link>
                </div>
            </div>
        </div>
    );
};

export default Privacy;
